### ISSUE TITLE
Running at boot on MacOS Catalina

### ISSUE THREAD

**Issue by swgrrt** [liquidctl/liquidctl#196]
I installed liquidctl via homebrew, which installs python as a dependency. So far liquidctl works via terminal.
When trying to set up the automatic start on boot, the guide says to create `/Library/LaunchDaemons/local.liquidcfg.plist ` with the path to the python binary:
`/Library/Frameworks/Python.framework/Versions/?.?/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

The problem is that I do not have a „Python.framework“ folder under „/Library/Frameworks“.
I guess this is because homebrew installs python to it‘s own folder.

Can you please help me on how to modify the liquidcfg.plist file in order to make it work?

**Comment by jonasmalacofilho** [comment]
@swgrrt

Hey, I just realized GitHub failed to notify me of this issue, and that I missed in later triages.  Sorry about that.

Because of how homebrew tries to isolate everything, getting things installed with it to run properly in the system context/profile is a bit nebulous.  Try removing the `PATH` override and seeing how (if) the daemon fails to launch, and we'll go from there.

**Comment by swgrrt** [comment]
Unfortunately I ditched my hackintosh in favor of linux, so I can not try this. Hopefully this still helps others having this problem.

**Comment by jonasmalacofilho** [comment]
Oh, still, thanks for letting me know about this potential problem.

---

@CaseySJ, do you know anything about this?

**Comment by CaseySJ** [comment]
> @CaseySJ, do you know anything about this?

@jonasmalacofilho @swgrrt 

Please refer to a detailed guide I put together (link below). It accommodates both (a) launch at login and (b) launch at wake-from-sleep.

https://www.tonymacx86.com/threads/gigabyte-z490-vision-d-thunderbolt-3-i5-10400-amd-rx-580.298642/post-2138475

**Comment by jonasmalacofilho** [comment]
Thanks, @CaseySJ!
