### ISSUE TITLE
NZXT Kraken Z (Z53) no fan rpm reported, but fans working correctly

### ISSUE THREAD

**Issue by dirusulixes** [liquidctl/liquidctl#376]
When running 
```
liquidctl --match kraken status
``` 
I get:

```
NZXT Kraken Z (Z53, Z63 or Z73) (experimental)
├── Liquid temperature    28.0  °C
├── Pump speed            2678  rpm
├── Pump duty               90  %
├── Fan speed                0  rpm
└── Fan duty                60  %
```

However the fans managed by the Kraken Z are spinning and I can change that using `set fan speed`

- Affected device: NZXT Kraken Z (Z53)
- Operating system: Arch Linux
- Liquidctl version: Arch Linux `liquidctl` package, version `1.7.1-1`

**Comment by jonasmalacofilho** [comment]
When you have a fan splitter, only one of the connectors (usually the first) will have the sense pin and, thus, will be able to read the fan speed.

Because of that, if there isn't a fan connected to that position (the most common issue), or if there's an issue with it or that connector, you wont see any fan speed.  Still, the fan itself (and other fans on the chain) may still work normally, since it is responsible for adjusting its own rotation speed according to the PWM duty cycle it receives through another pin (that one shared by all connectors on the chain).
