### ISSUE TITLE
H115i PRO XT

### ISSUE THREAD

**Issue by galtline** [liquidctl/liquidctl#418]
Please describe the issue or request as clearly and completely as possible.

Getting The following:

$ liquidctl --match H115i set sync color fixed 0080ff
ERROR: Error: missing --unsafe features for Corsair H115i Pro XT (experimental): 'pro_xt_lighting'
ERROR: More information is provided in the corresponding device guide

**Comment by jonasmalacofilho** [comment]
On the version you have, lighting control of Pro XT devices is experimental and requires the `--unsafe pro_xt_lighting` flag on all related commands.

By the way, you may want to consider updating liquidctl: 1.5.1 is already almost a year old, and there have been some (admittedly small) improvements to the Pro XT driver since.

P.S. Will move this to the Discussions tab (Q&A section).
