### ISSUE TITLE
Kraken X73

### ISSUE THREAD

**Issue by d7eeem** [liquidctl/liquidctl#473]
Sorry if i seem a bit rude i am frustrated  
If i can’t control the fans on it with liquidctl how can i manage it i am setting and the fans on full speed as if i am in a data center

If i buy nzxt fan contrller will it work ???

**Comment by jonasmalacofilho** [comment]
That specific device is _physically_ incapable of powering or controlling fan speeds.

(Which makes me wonder: are you sure it's a X73?)

> If i buy nzxt fan contrller will it work ???

Any fan controller supported by liquidctl would allow you to control fans (through liquidctl), but you should probably still check the specific features and limitations that apply to what you're thinking of buying.

For example, fan speed profiles are only natively (== in hardware) supported by a few controllers, and even then you won't have out-of-the-box access to neither coolant nor CPU temperature.  Software-based profiles can mitigate this (e.g. with your own script, or maybe with the `extra/yoda` script that we ship), but that isn't always appropriate, mainly due to reliability concerns (and you said "as if i am in a data center").
