### ISSUE TITLE
Support for UnRaid?

### ISSUE THREAD

**Issue by KastanDay** [liquidctl/liquidctl#500]
Is there support for UnRaid? I raised an issue on this repo with little success: https://github.com/avpnusr/liquidctl-docker/issues/3

Thank you!

**Comment by jonasmalacofilho** [comment]
> Is there support for UnRaid?

It's been known to work, but I'm not personally testing/using it on that platform.

For what its worth, sometime ago I used Docker for some testing, and it also worked fine.

> I raised an issue on this repo [...]: https://github.com/avpnusr/liquidctl-docker/issues/3

That's clearly a Docker usage error.  But I don't remember what exactly Docker accepts as a value for `--device`, and that might also change between Docker versions.  So, if I were you, I would start by checking the Docker documentation.

Totally unrelated to your problem, but `--privileged` might not be what you want/need.  If so, you might be able to adapt our udev rules (see `extra/linux/*.rules`) to avoid it.

> [...] **with little success:** https://github.com/avpnusr/liquidctl-docker/issues/3

From what I can see you opened this issue only 4 _minutes_ after that other one, so that statement might be a little premature...

---

I'm going to close this issue since your problem relates to liquidctl-docker and starting the Docker container itself.

If you/anyone is willing to open a PR for first-party Docker support in this repo, then please open a new issue and/or continue to comment here anyway.
