### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/hidraw/hidraw3/device/driver/module

### ISSUE THREAD

**Issue by myszkin81** [liquidctl/liquidctl#502]
On version 1.10.0 `liquidctl list` (and other options) give me
`FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/hidraw/hidraw3/device/driver/module'`

but all is fine on 1.8.1

```
liquidctl list
Device #0: Corsair Commander Pro
Device #1: Corsair Hydro H100i Platinum SE
```

**Comment by jonasmalacofilho** [comment]
My first guess is that your kernel has been built with `CONFIG_SENSORS_CORSAIR_CPRO=y`, instead of `=m`... and that we need to figure out a way to get the driver name in that scenario.

But can you first please provide more context about your environment?  The bug report template already asked for some specific pieces of information, and, in addition to those, please _also_ include your kernel configuration and the output from:

```
$ grep -rn . /sys/class/hidraw/hidraw3/
```

**Comment by myszkin81** [comment]
Recompiling kernel with modules solved it but why it was okay for previous liquidctl versions like 1.8.1

```
wgen /home/jam # grep -rn . /sys/class/hidraw/hidraw3
/sys/class/hidraw/hidraw3/uevent:1:MAJOR=241
/sys/class/hidraw/hidraw3/uevent:2:MINOR=3
/sys/class/hidraw/hidraw3/uevent:3:DEVNAME=hidraw3
/sys/class/hidraw/hidraw3/power/runtime_active_time:1:0
/sys/class/hidraw/hidraw3/power/runtime_status:1:unsupported
grep: /sys/class/hidraw/hidraw3/power/autosuspend_delay_ms: Input/output error
/sys/class/hidraw/hidraw3/power/runtime_suspended_time:1:0
/sys/class/hidraw/hidraw3/power/control:1:auto
/sys/class/hidraw/hidraw3/dev:1:241:3
```

kernel config: http://dpaste.com/HXU6AJUWC

system: gentoo Linux wgen 5.19.3-gentoo #5 SMP PREEMPT_DYNAMIC Wed Aug 31 17:36:51 EEST 2022 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

liquidctl v1.10.0 (Linux-5.19.3-gentoo-x86_64-AMD_Ryzen_9_5900X_12-Core_Processor-with-glibc2.35)

**Comment by jonasmalacofilho** [comment]
Thanks!

And what about?

```
$ ls -l /sys/class/hidraw/hidraw3/device/
$ ls -l /sys/class/hidraw/hidraw3/device/driver/
```

But please make sure that hidraw3 still refers to the same device as before (which we think is the Commander Pro), and with `corsair_cpro` (back as) built as a built-in driver.

In fact, is the grep output above with that driver built-in or as a loaded module?

---

I would still like to see the (complete) failing liquidctl output with `--debug`, as asked in the bug report template.  It contains further information about your environment (that I would otherwise would need to ask you anyway), and confirms which device and driver are specifically affected.  So far it seems I've been right in guessing that it's just the Commander Pro, but that depends on everything else working correctly, which might not necessarily be the case...

**Comment by jonasmalacofilho** [comment]
> but why it was okay for previous liquidctl versions like 1.8.1

That's because liquidctl 1.8.1 didn't know about hwmon drivers, and didn't try to leverage and avoid conflicts with them.

**Comment by jonasmalacofilho** [comment]
The issue should be fixed in the `main` branch.  Please let me know if that's not the case.
