### ISSUE TITLE
h150i not showing up on new ubuntu install

### ISSUE THREAD

**Issue by buddyochoa2** [liquidctl/liquidctl#540]
I've just installed Ubuntu and am attempting to get this working with my Corsair h150i. When I do the list command it doesn't return anything. I'm new to linux so I'm not sure what information you would need to be able to help. I am running Ubuntu 22.10

**Comment by jonasmalacofilho** [comment]
If you installed liquidctl from the Ubuntu repositories, it's a terribly outdated version, and that probably explains your problem.

---

Otherwise, check the _Troubleshooting_ section in the README. And if that also doesn't fix your issue, then please open a bug report: the bug report template will guide you though what information to provide us.
